# Generated by Django 4.2 on 2023-04-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LoginApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="project",
            field=models.CharField(default="", max_length=20),
        ),
    ]
