# Generated by Django 4.2 on 2023-04-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LoginApp", "0002_code_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="code",
            name="project",
        ),
    ]
