# Generated by Django 4.1.7 on 2023-04-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0002_article_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
