# Generated by Django 4.1.7 on 2023-04-03 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0009_alter_article_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.AddField(
            model_name="article",
            name="categorykey",
            field=models.ForeignKey(
                db_column="category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BlogApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 3, 19, 15, 47, 316658)
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
