# Generated by Django 4.1.7 on 2023-04-04 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0010_remove_article_category_article_categorykey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 11, 1, 14, 240090)
            ),
        ),
    ]
