# Generated by Django 4.1.7 on 2023-04-04 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0011_alter_article_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categorykey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BlogApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 11, 3, 48, 466843)
            ),
        ),
    ]
