# Generated by Django 4.1.7 on 2023-04-04 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0014_alter_article_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 11, 10, 28, 115473)
            ),
        ),
    ]
