# Generated by Django 4.1.7 on 2023-04-04 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0017_alter_article_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="categorykey",
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 20, 57, 27, 460431)
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
