# Generated by Django 4.1.7 on 2023-04-05 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0018_remove_article_categorykey_article_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 5, 18, 2, 44, 178753)
            ),
        ),
    ]
