# Generated by Django 4.1.7 on 2023-04-08 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0021_alter_article_date_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 8, 17, 57, 6, 806972)
            ),
        ),
    ]
