# Generated by Django 4.2 on 2023-05-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": "database_name",
                "verbose_name_plural": "database_names",
            },
        ),
    ]
