# Generated by Django 4.2 on 2023-05-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-create_dt", "author"),
                "verbose_name": "MyPost",
                "verbose_name_plural": "MyPosts",
            },
        ),
    ]
