# Generated by Django 4.2 on 2023-04-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TodoApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="deadline",
        ),
    ]
