# Generated by Django 4.2 on 2023-04-05 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TodoApp", "0002_remove_todo_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 6, 0, 4, 49, 131345)
            ),
        ),
    ]
