# Generated by Django 4.2 on 2023-04-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TodoApp", "0003_todo_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="date",
        ),
    ]
